language: clojure
cache:
  directories:
    - node_modules
before_cache:
  - rm -rf $TRAVIS_BUILD_DIR/node_modules/.cache
before_install:
- "./begin-development.sh"
jobs:
  include:
  - stage: test
    script: ./test.sh
stages:
- test


